---
- name: Dependencies
  ansible.builtin.package:
      name:
          - base-devel
      state: latest
  become: yes

- name: Clone
  ansible.builtin.git:
      clone: yes
      depth: 1
      dest: "{{ ansible_user_dir }}/repo/yay/"
      force: yes
      repo: https://aur.archlinux.org/yay.git
      single_branch: yes
      update: yes
      version: master
  register: clone

- name: makepkg --noconfirm -si
  become: false
  command: makepkg --noconfirm -si
  args:
      chdir: "{{ ansible_user_dir }}/repo/yay/"
      creates: /usr/bin/yay
