---
- name: Install
  ansible.builtin.package:
      name:
          - zsh
      state: latest
  become: yes

- name: Set ZSH to default shell
  user:
      name: "{{ ansible_env['USER'] }}"
      shell: /usr/bin/zsh
  become: yes
