---
- name: Existing install
  stat:
      path: "{{ ansible_user_dir }}/.oh-my-zsh"
  register: install

- name: Download oh-my-zsh
  get_url:
      dest: /tmp/zsh-install.sh
      mode: 0755
      url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
  when: not install.stat.exists

- name: Execute zsh-install.sh
  shell: /tmp/zsh-install.sh
  when: not install.stat.exists

- name: Remove zsh-install.sh
  file:
      path: /tmp/zsh-install.sh
      state: absent

- name: Copy .zshrc
  ansible.builtin.template:
      dest: "{{ ansible_user_dir }}/.zshrc"
      src: .zshrc.j2

- name: Clone zsh-autosuggestions
  ansible.builtin.git:
      clone: yes
      depth: 1
      dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
      repo: https://github.com/zsh-users/zsh-autosuggestions
      single_branch: yes
      update: yes
      version: master

- name: Clone zsh-syntax-highlighting
  ansible.builtin.git:
      clone: yes
      depth: 1
      dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
      repo: https://github.com/zsh-users/zsh-syntax-highlighting
      single_branch: yes
      update: yes
      version: master

- name: Clone powerlevel10k
  ansible.builtin.git:
      clone: yes
      depth: 1
      dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/powerlevel10k"
      repo: https://github.com/romkatv/powerlevel10k
      single_branch: yes
      update: yes
      version: master

- name: Copy .p10k.zsh
  ansible.builtin.template:
      dest: "{{ ansible_user_dir }}/.p10k.zsh"
      src: .p10k.zsh.j2
