---
- name: Clone
  ansible.builtin.git:
      clone: yes
      depth: 1
      dest: "{{ ansible_user_dir }}/Development/repository/github.com/nerd-fonts"
      force: yes
      repo: https://github.com/ryanoasis/nerd-fonts.git
      single_branch: yes
      update: yes
      version: master
  register: clone

- name: Install
  ansible.builtin.shell: ./install.sh
  args:
      chdir: "{{ ansible_user_dir }}/Development/repository/github.com/nerd-fonts"
  when: clone.changed
