---
- name: Install
  ansible.builtin.package:
      name:
          - lightdm
          - lightdm-slick-greeter
      state: latest
  become: yes

- name: Enable lightdm service
  ansible.builtin.systemd:
      name: lightdm
      enabled: yes
