---
- name: Install
  ansible.builtin.package:
      name:
          - alacritty
      state: latest
  become: yes

- name: Config folder
  ansible.builtin.file:
      mode: "0755"
      path: "{{ ansible_user_dir }}/.config/alacritty"
      state: directory

- name: Configuration
  ansible.builtin.template:
      dest: "{{ ansible_user_dir }}/.config/alacritty/alacritty.yaml"
      src: "alacritty.yaml.j2"
